title: Yo! 🚀 Welcome to my personal corner of Internet!
description: "This the website of Marco Cuscunà"
github_username: Markus2409

remote_theme: "mmistakes/minimal-mistakes@4.24.0"  # consigliato
minimal_mistakes_skin: neon
search: true

markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
include:
  - _pages

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag   # <— aggiunto

author:
  name   : "Marco Cuscunà"
  avatar : "https://avatars.githubusercontent.com/u/190472880?v=4"
  bio    : "My name is Marco Cuscunà and i am a computing lover."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Markus2409"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/marcocuscu"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Markus2409"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/marcocuscu"

defaults:
  - scope: { path: "", type: posts }
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope: { path: "_pages", type: pages }
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
